import type { ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

export type CmsTableColumn<T> = { key: string; header: string; className?: string; render: (row: T) => ReactNode };

export function CmsTable<T extends { id: string }>({ columns, rows, toolbar, emptyContent, selectable = false, selectedIds = [], onSelectRow, onSelectAll }: { columns: CmsTableColumn<T>[]; rows: T[]; toolbar?: ReactNode; emptyContent?: ReactNode; selectable?: boolean; selectedIds?: string[]; onSelectRow?: (row: T, selected: boolean) => void; onSelectAll?: (selected: boolean) => void }) {
  const allSelected = rows.length > 0 && rows.every((row) => selectedIds.includes(row.id));
  return <div className="overflow-hidden rounded-2xl border border-zinc-200/80 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)] dark:border-zinc-800/80 dark:bg-zinc-900/60">{toolbar && <div className="flex min-h-14 flex-wrap items-center justify-between gap-3 border-b border-zinc-100 px-5 py-3 dark:border-zinc-800">{toolbar}</div>}<Table className="min-w-[720px]"><TableHeader className="bg-zinc-50/70 dark:bg-zinc-900/80"><TableRow className="hover:bg-transparent">{selectable && <TableHead className="w-12 pl-5 pr-1"><input type="checkbox" aria-label="Pilih semua baris" checked={allSelected} onChange={(event) => onSelectAll?.(event.target.checked)} className="size-4 rounded border-zinc-300 accent-violet-500" /></TableHead>}{columns.map((column) => <TableHead key={column.key} className={`h-11 px-4 text-[11px] font-medium text-zinc-500 dark:text-zinc-400 ${column.className ?? ''}`}>{column.header}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length === 0 ? <TableRow className="hover:bg-transparent"><TableCell colSpan={columns.length + (selectable ? 1 : 0)} className="h-40 text-center">{emptyContent ?? <span className="text-sm text-zinc-500">Belum ada data.</span>}</TableCell></TableRow> : rows.map((row) => { const selected = selectedIds.includes(row.id); return <TableRow key={row.id} data-state={selected ? 'selected' : undefined} className="group h-[68px] border-zinc-100/90 hover:bg-zinc-50/80 dark:border-zinc-800/80 dark:hover:bg-zinc-800/30">{selectable && <TableCell className="w-12 pl-5 pr-1"><input type="checkbox" aria-label="Pilih baris" checked={selected} onChange={(event) => onSelectRow?.(row, event.target.checked)} className="size-4 rounded border-zinc-300 accent-violet-500" /></TableCell>}{columns.map((column) => <TableCell key={column.key} className={`px-4 py-3 ${column.className ?? ''}`}>{column.render(row)}</TableCell>)}</TableRow>; })}</TableBody></Table></div>;
}

export function CmsTableTabs({ tabs, activeTab, onChange }: { tabs: Array<{ value: string; label: string }>; activeTab: string; onChange: (value: string) => void }) {
  return <div className="inline-flex items-center gap-1 rounded-xl bg-zinc-100 p-1 dark:bg-zinc-800">{tabs.map((tab) => <button key={tab.value} type="button" onClick={() => onChange(tab.value)} className={`rounded-lg px-4 py-1.5 text-sm font-medium transition-colors ${activeTab === tab.value ? 'bg-white text-zinc-900 shadow-sm dark:bg-zinc-700 dark:text-white' : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'}`}>{tab.label}</button>)}</div>;
}

export function CmsTableSkeleton({ columns = 5, rows = 6 }: { columns?: number; rows?: number }) {
  return <div className="overflow-hidden rounded-2xl border border-zinc-200/80 bg-white shadow-sm dark:border-zinc-800/80 dark:bg-zinc-900/60"><div className="h-11 animate-pulse bg-zinc-100/80 dark:bg-zinc-800/70" /> <div className="space-y-0">{Array.from({ length: rows }, (_, row) => <div key={row} className="flex h-[58px] items-center gap-4 border-t border-zinc-100 px-5 dark:border-zinc-800">{Array.from({ length: columns }, (_, column) => <div key={column} className={`h-3 animate-pulse rounded bg-zinc-200/80 dark:bg-zinc-800 ${column === 0 ? 'w-5' : column === columns - 1 ? 'ml-auto w-24' : 'w-32'}`} />)}</div>)}</div></div>;
}

export function CmsPagination({ page, totalPages, totalItems, pageSize, itemLabel = 'item', onPageChange }: { page: number; totalPages: number; totalItems: number; pageSize: number; itemLabel?: string; onPageChange: (page: number) => void }) {
  if (totalPages <= 1) return null;
  const start = (page - 1) * pageSize + 1;
  const end = Math.min(page * pageSize, totalItems);
  return <div className="flex flex-col gap-3 border-t border-zinc-200 pt-4 dark:border-zinc-800 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-zinc-500">Menampilkan {start}–{end} dari {totalItems} {itemLabel}</p><div className="flex items-center gap-1"><Button variant="outline" size="icon-sm" aria-label="Halaman sebelumnya" disabled={page === 1} onClick={() => onPageChange(Math.max(1, page - 1))}><ChevronLeft className="size-4" /></Button>{Array.from({ length: totalPages }, (_, index) => index + 1).map((pageNumber) => <Button key={pageNumber} variant={pageNumber === page ? 'default' : 'outline'} size="sm" className="h-8 min-w-8 px-2" aria-label={`Buka halaman ${pageNumber}`} onClick={() => onPageChange(pageNumber)}>{pageNumber}</Button>)}<Button variant="outline" size="icon-sm" aria-label="Halaman berikutnya" disabled={page === totalPages} onClick={() => onPageChange(Math.min(totalPages, page + 1))}><ChevronRight className="size-4" /></Button></div></div>;
}
