import { Booking, PackageItem, AdminNotification } from '@/types/admin';

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg-1',
    name: 'Solo Kebaya Signature',
    slug: 'solo-kebaya',
    category: 'Solo',
    price: 450000,
    durationMinutes: 45,
    maxPeople: 1,
    editedPhotos: 10,
    allRawIncluded: true,
    isActive: true,
    totalBookings: 142,
  },
  {
    id: 'pkg-2',
    name: 'Duo Bestie Graduation',
    slug: 'duo-bestie',
    category: 'Squad',
    price: 750000,
    durationMinutes: 60,
    maxPeople: 2,
    editedPhotos: 15,
    allRawIncluded: true,
    isActive: true,
    totalBookings: 98,
  },
  {
    id: 'pkg-3',
    name: 'Squad Circle (4-6 Orang)',
    slug: 'squad-circle',
    category: 'Squad',
    price: 1250000,
    durationMinutes: 90,
    maxPeople: 6,
    editedPhotos: 25,
    allRawIncluded: true,
    isActive: true,
    totalBookings: 164,
  },
  {
    id: 'pkg-4',
    name: 'Family Heritage Portrait',
    slug: 'family-heritage',
    category: 'Family',
    price: 1500000,
    durationMinutes: 90,
    maxPeople: 8,
    editedPhotos: 20,
    allRawIncluded: true,
    isActive: true,
    totalBookings: 87,
  },
  {
    id: 'pkg-5',
    name: '35mm Analog Film Experience',
    slug: 'film-analog-35mm',
    category: 'Cinematic',
    price: 950000,
    durationMinutes: 60,
    maxPeople: 2,
    editedPhotos: 36,
    allRawIncluded: true,
    isActive: true,
    totalBookings: 54,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    bookingCode: 'KYA-2026-081',
    customerName: 'Anisa Rahmawati',
    customerPhone: '081234567890',
    customerEmail: 'anisa.rahma@gmail.com',
    university: 'Universitas Diponegoro (Undip)',
    faculty: 'Fakultas Ekonomika dan Bisnis',
    packageName: 'Solo Kebaya Signature',
    packagePrice: 450000,
    addons: [
      { id: 'ad-1', name: 'Cetak Frame Kayu 12R', price: 120000 },
      { id: 'ad-2', name: 'Express Edit 24 Jam', price: 75000 },
    ],
    totalPrice: 645000,
    sessionDate: '2026-08-25',
    timeSlot: '09:00 - 10:00',
    location: 'Studio Kayastory (Tembalang)',
    photographer: 'Bima Satria (Lead)',
    status: 'PENDING_VERIFICATION',
    paymentStatus: 'WAITING_CONFIRMATION',
    paymentProofUrl: 'https://images.unsplash.com/photo-1554415707-9e49017a1265?auto=format&fit=crop&w=800&q=80',
    paymentAmount: 645000,
    paymentBank: 'BCA (A.N. Anisa Rahmawati)',
    paymentDate: '2026-08-24 19:40',
    notes: 'Mau tone warm vintage 35mm, bawa 2 kebaya ganti.',
    createdAt: '2026-08-24 19:35',
  },
  {
    id: 'bk-102',
    bookingCode: 'KYA-2026-082',
    customerName: 'Dimas Pratama & Squad',
    customerPhone: '085712349988',
    customerEmail: 'dimas.pratama@students.unnes.ac.id',
    university: 'Universitas Negeri Semarang (Unnes)',
    faculty: 'Fakultas Ilmu Keolahragaan',
    packageName: 'Squad Circle (4-6 Orang)',
    packagePrice: 1250000,
    addons: [
      { id: 'ad-3', name: 'Extra 5 Edited Photos', price: 100000 },
    ],
    totalPrice: 1350000,
    sessionDate: '2026-08-25',
    timeSlot: '13:30 - 15:00',
    location: 'Outdoor Rektorat Unnes',
    photographer: 'Rian Maulana',
    status: 'PENDING_VERIFICATION',
    paymentStatus: 'WAITING_CONFIRMATION',
    paymentProofUrl: 'https://images.unsplash.com/photo-1554415707-9e49017a1265?auto=format&fit=crop&w=800&q=80',
    paymentAmount: 500000, // DP
    paymentBank: 'Mandiri (A.N. Dimas Pratama)',
    paymentDate: '2026-08-24 20:15',
    notes: 'Total ada 5 orang wisudawan bareng. DP 500k dulu.',
    createdAt: '2026-08-24 20:10',
  },
  {
    id: 'bk-103',
    bookingCode: 'KYA-2026-083',
    customerName: 'Nadia Salsabila',
    customerPhone: '081390887766',
    customerEmail: 'nadia.salsa@gmail.com',
    university: 'Universitas Dian Nuswantoro (Udinus)',
    faculty: 'Fakultas Ilmu Komputer',
    packageName: 'Duo Bestie Graduation',
    packagePrice: 750000,
    addons: [],
    totalPrice: 750000,
    sessionDate: '2026-08-26',
    timeSlot: '10:30 - 11:30',
    location: 'Studio Kayastory (Tembalang)',
    photographer: 'Bima Satria (Lead)',
    status: 'CONFIRMED',
    paymentStatus: 'PAID_FULL',
    paymentProofUrl: 'https://images.unsplash.com/photo-1554415707-9e49017a1265?auto=format&fit=crop&w=800&q=80',
    paymentAmount: 750000,
    paymentBank: 'QRIS BCA',
    paymentDate: '2026-08-23 15:20',
    notes: 'Sama sahabat satu bimbingan skripsi. Sudah DP & Lunas.',
    invoiceNumber: 'INV-KYA-2026-083',
    createdAt: '2026-08-23 15:00',
  },
  {
    id: 'bk-104',
    bookingCode: 'KYA-2026-084',
    customerName: 'Keluarga Ir. Hartono (Wisuda Rizky)',
    customerPhone: '082133445566',
    customerEmail: 'hartono.semarang@gmail.com',
    university: 'Politeknik Negeri Semarang (Polines)',
    faculty: 'Teknik Mesin',
    packageName: 'Family Heritage Portrait',
    packagePrice: 1500000,
    addons: [
      { id: 'ad-1', name: 'Cetak Frame Kayu 12R', price: 120000 },
      { id: 'ad-4', name: 'Album Eksklusif Kulit', price: 350000 },
    ],
    totalPrice: 1970000,
    sessionDate: '2026-08-26',
    timeSlot: '15:30 - 17:00',
    location: 'Studio Kayastory (Tembalang)',
    photographer: 'Arif Wicaksono',
    status: 'CONFIRMED',
    paymentStatus: 'PAID_FULL',
    paymentProofUrl: 'https://images.unsplash.com/photo-1554415707-9e49017a1265?auto=format&fit=crop&w=800&q=80',
    paymentAmount: 1970000,
    paymentBank: 'BCA (A.N. Bambang Hartono)',
    paymentDate: '2026-08-22 11:05',
    notes: 'Bawa orang tua + 2 adik.',
    invoiceNumber: 'INV-KYA-2026-084',
    createdAt: '2026-08-22 10:45',
  },
  {
    id: 'bk-105',
    bookingCode: 'KYA-2026-085',
    customerName: 'Fadhil Al-Ghifari',
    customerPhone: '087812903344',
    customerEmail: 'fadhil.alghi@gmail.com',
    university: 'UIN Walisongo Semarang',
    faculty: 'Fakultas Syariah & Hukum',
    packageName: '35mm Analog Film Experience',
    packagePrice: 950000,
    addons: [],
    totalPrice: 950000,
    sessionDate: '2026-08-27',
    timeSlot: '08:30 - 09:30',
    location: 'Kota Lama Semarang (Outdoor)',
    photographer: 'Bima Satria (Lead)',
    status: 'CONFIRMED',
    paymentStatus: 'PAID_DP',
    paymentProofUrl: 'https://images.unsplash.com/photo-1554415707-9e49017a1265?auto=format&fit=crop&w=800&q=80',
    paymentAmount: 500000,
    paymentBank: 'BSI (A.N. Fadhil)',
    paymentDate: '2026-08-24 10:00',
    notes: 'Sesi outdoor di depan Gereja Blenduk Kota Lama.',
    invoiceNumber: 'INV-KYA-2026-085',
    createdAt: '2026-08-24 09:30',
  },
  {
    id: 'bk-106',
    bookingCode: 'KYA-2026-086',
    customerName: 'Clara Michelle',
    customerPhone: '089612345678',
    customerEmail: 'clara.m@unika.ac.id',
    university: 'SCU (Unika Soegijapranata)',
    faculty: 'Fakultas Arsitektur dan Desain',
    packageName: 'Solo Kebaya Signature',
    packagePrice: 450000,
    addons: [],
    totalPrice: 450000,
    sessionDate: '2026-08-28',
    timeSlot: '11:00 - 12:00',
    location: 'Studio Kayastory (Tembalang)',
    photographer: 'Rian Maulana',
    status: 'COMPLETED',
    paymentStatus: 'PAID_FULL',
    paymentAmount: 450000,
    paymentBank: 'BCA (A.N. Clara M)',
    paymentDate: '2026-08-20 14:00',
    notes: 'File foto raw dan edit sudah diserahkan via Google Drive.',
    invoiceNumber: 'INV-KYA-2026-086',
    createdAt: '2026-08-20 13:40',
  },
];

export const INITIAL_NOTIFICATIONS: AdminNotification[] = [
  {
    id: 'notif-1',
    title: 'Pembayaran Baru Perlu Verifikasi',
    message: 'Anisa Rahmawati (Undip) mengunggah bukti transfer BCA Rp 645.000.',
    type: 'PAYMENT_PROOF',
    timestamp: '5 menit yang lalu',
    read: false,
    bookingId: 'bk-101',
  },
  {
    id: 'notif-2',
    title: 'Booking Baru Masuk',
    message: 'Dimas Pratama reservasi Squad Circle untuk 25 Agustus 2026.',
    type: 'BOOKING_NEW',
    timestamp: '25 menit yang lalu',
    read: false,
    bookingId: 'bk-102',
  },
  {
    id: 'notif-3',
    title: 'Invoice Terkirim Otomatis',
    message: 'Invoice INV-KYA-2026-085 sukses dikirim ke WhatsApp Fadhil Al-Ghifari.',
    type: 'SYSTEM',
    timestamp: '2 jam yang lalu',
    read: true,
    bookingId: 'bk-105',
  },
];

export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}
